// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicesDatabase.Core;

#nullable disable

namespace ServicesDatabase.Migrations
{
    [DbContext(typeof(ServicesDbConnection))]
    partial class ServicesDbConnectionModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServicesDatabase.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cardiologist Initial",
                            ServiceCategoryId = 1,
                            SpecializationId = 1,
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cardiologist Follow-up",
                            ServiceCategoryId = 1,
                            SpecializationId = 1,
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Neurologist Initial",
                            ServiceCategoryId = 1,
                            SpecializationId = 2,
                            isActive = true
                        },
                        new
                        {
                            Id = 4,
                            Name = "Surgeon Consultation",
                            ServiceCategoryId = 1,
                            SpecializationId = 3,
                            isActive = false
                        },
                        new
                        {
                            Id = 5,
                            Name = "X-Ray Chest",
                            ServiceCategoryId = 2,
                            SpecializationId = 4,
                            isActive = true
                        },
                        new
                        {
                            Id = 6,
                            Name = "MRI Brain",
                            ServiceCategoryId = 2,
                            SpecializationId = 4,
                            isActive = true
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ultrasound Abdomen",
                            ServiceCategoryId = 2,
                            SpecializationId = 4,
                            isActive = false
                        },
                        new
                        {
                            Id = 8,
                            Name = "Complete Blood Count",
                            ServiceCategoryId = 3,
                            SpecializationId = 5,
                            isActive = true
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lipid Panel",
                            ServiceCategoryId = 3,
                            SpecializationId = 5,
                            isActive = true
                        },
                        new
                        {
                            Id = 10,
                            Name = "Vitamin D",
                            ServiceCategoryId = 3,
                            SpecializationId = 5,
                            isActive = false
                        });
                });

            modelBuilder.Entity("ServicesDatabase.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSlotSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Consultation",
                            TimeSlotSize = 30
                        },
                        new
                        {
                            Id = 2,
                            Name = "Diagnostics",
                            TimeSlotSize = 60
                        },
                        new
                        {
                            Id = 3,
                            Name = "Analyses",
                            TimeSlotSize = 45
                        });
                });

            modelBuilder.Entity("ServicesDatabase.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActiove")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General Therapy",
                            isActiove = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cardiology",
                            isActiove = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dentistry",
                            isActiove = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
